# Student Performance Analysis

This project analyzes student marks from a CSV file.

We will:
- Load CSV data
- Handle missing values
- Add Total and Average columns
- Find Top 3 students
- Compute department-wise averages
- Filter high-performing students

## Objective

To perform data preprocessing and analysis using pandas:

- Data cleaning
- Feature engineering (Total, Average)
- Group analysis
- Filtering based on conditions

In [1]:
import pandas as pd

## Load Dataset

We read the CSV file containing student marks.

In [3]:
import pandas as pd
import numpy as np

# Creating data that fits your specific analysis
data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'name': ['Arjun', 'Sanya', 'Vikram', 'Priya', 'Rohan', 'Anjali', 'Karan', 'Meera'],
    'dept': ['CS', 'CS', 'ECE', 'MECH', 'ECE', 'CS', 'MECH', 'ECE'],
    'maths': [85, 92, np.nan, 45, 88, 76, 90, 82],      # One missing value
    'science': [78, np.nan, 85, 30, 92, 80, 88, 77],    # One missing value
    'english': [90, 85, 70, 50, np.nan, 82, 95, 79]     # One missing value
}

df_new = pd.DataFrame(data)

# Save to CSV
df_new.to_csv('students.csv', index=False)

print("New 'students.csv' created with 'dept' and subject columns!")

New 'students.csv' created with 'dept' and subject columns!

In [4]:
df = pd.read_csv("students.csv")

df

   student_id    name  dept  maths  science  english
0           1   Arjun    CS   85.0     78.0     90.0
1           2   Sanya    CS   92.0      NaN     85.0
2           3  Vikram   ECE    NaN     85.0     70.0
3           4   Priya  MECH   45.0     30.0     50.0
4           5   Rohan   ECE   88.0     92.0      NaN
5           6  Anjali    CS   76.0     80.0     82.0
6           7   Karan  MECH   90.0     88.0     95.0
7           8   Meera   ECE   82.0     77.0     79.0

## Handle Missing Values

We check for missing values and fill them with 0 (or mean if required).

In [5]:
print(df.isnull().sum())

df.fillna(0, inplace=True)

student_id    0
name          0
dept          0
maths         1
science       1
english       1
dtype: int64

## Add Total and Average Columns

In [6]:
df["total"] = df["maths"] + df["science"] + df["english"]

df["average"] = df["total"] / 3

df

   student_id    name  dept  maths  science  english  total    average
0           1   Arjun    CS   85.0     78.0     90.0  253.0  84.333333
1           2   Sanya    CS   92.0      0.0     85.0  177.0  59.000000
2           3  Vikram   ECE    0.0     85.0     70.0  155.0  51.666667
3           4   Priya  MECH   45.0     30.0     50.0  125.0  41.666667
4           5   Rohan   ECE   88.0     92.0      0.0  180.0  60.000000
5           6  Anjali    CS   76.0     80.0     82.0  238.0  79.333333
6           7   Karan  MECH   90.0     88.0     95.0  273.0  91.000000
7           8   Meera   ECE   82.0     77.0     79.0  238.0  79.333333

## Top 3 Students Based on Total Marks

In [7]:
top3 = df.sort_values(by="total", ascending=False).head(3)

top3

   student_id    name  dept  maths  science  english  total    average
6           7   Karan  MECH   90.0     88.0     95.0  273.0  91.000000
0           1   Arjun    CS   85.0     78.0     90.0  253.0  84.333333
5           6  Anjali    CS   76.0     80.0     82.0  238.0  79.333333

## Department-wise Average Marks

In [8]:
dept_avg = df.groupby("dept")[["maths", "science", "english", "total", "average"]].mean()

dept_avg

          maths    science    english       total    average
dept
CS    84.333333  52.666667  85.666667  222.666667  74.222222
ECE   56.666667  84.666667  49.666667  191.000000  63.666667
MECH  67.500000  59.000000  72.500000  199.000000  66.333333

## Students Scoring Above 75 in All Subjects

In [9]:
high_performers = df[
    (df["maths"] > 75) &
    (df["science"] > 75) &
    (df["english"] > 75)
]

high_performers

   student_id    name  dept  maths  science  english  total    average
0           1   Arjun    CS   85.0     78.0     90.0  253.0  84.333333
5           6  Anjali    CS   76.0     80.0     82.0  238.0  79.333333
6           7   Karan  MECH   90.0     88.0     95.0  273.0  91.000000
7           8   Meera   ECE   82.0     77.0     79.0  238.0  79.333333

## Conclusion

- We successfully cleaned and analyzed student data
- Added new computed features (total, average)
- Identified top performers
- Performed department-wise analysis

This demonstrates basic real-world data analysis using pandas.